In [1]:
import pandas as pd
from datasets import load_dataset

## empathetic_dialogues

In [7]:
empathetic_dialogues = load_dataset("empathetic_dialogues",trust_remote_code=True)
print("1")
print(empathetic_dialogues)

1
DatasetDict({
    train: Dataset({
        features: ['conv_id', 'utterance_idx', 'context', 'prompt', 'speaker_idx', 'utterance', 'selfeval', 'tags'],
        num_rows: 76673
    })
    validation: Dataset({
        features: ['conv_id', 'utterance_idx', 'context', 'prompt', 'speaker_idx', 'utterance', 'selfeval', 'tags'],
        num_rows: 12030
    })
    test: Dataset({
        features: ['conv_id', 'utterance_idx', 'context', 'prompt', 'speaker_idx', 'utterance', 'selfeval', 'tags'],
        num_rows: 10943
    })
})

In [8]:
empathetic_dialogues

DatasetDict({
    train: Dataset({
        features: ['conv_id', 'utterance_idx', 'context', 'prompt', 'speaker_idx', 'utterance', 'selfeval', 'tags'],
        num_rows: 76673
    })
    validation: Dataset({
        features: ['conv_id', 'utterance_idx', 'context', 'prompt', 'speaker_idx', 'utterance', 'selfeval', 'tags'],
        num_rows: 12030
    })
    test: Dataset({
        features: ['conv_id', 'utterance_idx', 'context', 'prompt', 'speaker_idx', 'utterance', 'selfeval', 'tags'],
        num_rows: 10943
    })
})

In [21]:
rows = []

for item in empathetic_dialogues["train"]:
    rows.append({
        "dataset": "empathetic_dialogues",
        "conversation_id": item["conv_id"],
        "role": "user" if item["speaker_idx"] == 0 else "assistant",
        "text": item["utterance"],
        "emotion": item["context"]
    })

df_empathetic = pd.DataFrame(rows)
df_empathetic.to_csv("./data/empathetic_dialogues_train.csv", index=False)
# df_empathetic_train
df_empathetic

,dataset,conversation_id,role,text,emotion
0,empathetic_dialogues,hit:0_conv:1,assistant,I remember going to see the fireworks with my ...,sentimental
1,empathetic_dialogues,hit:0_conv:1,user,Was this a friend you were in love with_comma_...,sentimental
2,empathetic_dialogues,hit:0_conv:1,assistant,This was a best friend. I miss her.,sentimental
3,empathetic_dialogues,hit:0_conv:1,user,Where has she gone?,sentimental
4,empathetic_dialogues,hit:0_conv:1,assistant,We no longer talk.,sentimental
...,...,...,...,...,...
76668,empathetic_dialogues,hit:12424_conv:24848,assistant,Yeah reminds me of the good old days. I miss ...,sentimental
76669,empathetic_dialogues,hit:12424_conv:24849,assistant,I woke up this morning to my wife telling me s...,surprised
76670,empathetic_dialogues,hit:12424_conv:24849,assistant,Oh hey that's awesome! That is awesome right?,surprised
76671,empathetic_dialogues,hit:12424_conv:24849,assistant,It is soooo awesome. We have been wanting a b...,surprised
76672,empathetic_dialogues,hit:12424_conv:24849,assistant,That is awesome!!!! Congratulations!,surprised

In [22]:

rows = []

for item in empathetic_dialogues["validation"]:
    rows.append({
        "dataset": "empathetic_dialogues",
        "conversation_id": item["conv_id"],
        "role": "user" if item["speaker_idx"] == 0 else "assistant",
        "text": item["utterance"],
        "emotion": item["context"]
    })

df_empathetic = pd.DataFrame(rows)
df_empathetic.to_csv("./data/empathetic_dialogues_validation.csv", index=False)
# df_empathetic_val
df_empathetic

,dataset,conversation_id,role,text,emotion
0,empathetic_dialogues,hit:3_conv:6,assistant,Today_comma_as i was leaving for work in the m...,terrified
1,empathetic_dialogues,hit:3_conv:6,assistant,Are you fine now?,terrified
2,empathetic_dialogues,hit:3_conv:6,assistant,Yeah_comma_i'm doing alright now_comma_ but wi...,terrified
3,empathetic_dialogues,hit:3_conv:6,assistant,Cool :) Is your car damaged a lot?,terrified
4,empathetic_dialogues,hit:3_conv:6,assistant,The car was badly damaged_comma_i veered outsi...,terrified
...,...,...,...,...,...
12025,empathetic_dialogues,hit:12361_conv:24722,assistant,tha is really cool what was your grade,prepared
12026,empathetic_dialogues,hit:12392_conv:24785,assistant,One of my coworkers has been arguing with his ...,furious
12027,empathetic_dialogues,hit:12392_conv:24785,assistant,What are they arguing about?,furious
12028,empathetic_dialogues,hit:12392_conv:24785,assistant,Everything and anything. It's annoying_comma_ ...,furious
12029,empathetic_dialogues,hit:12392_conv:24785,assistant,That's so ridiculous!,furious

In [23]:

rows = []

for item in empathetic_dialogues["test"]:
    rows.append({
        "dataset": "empathetic_dialogues",
        "conversation_id": item["conv_id"],
        "role": "user" if item["speaker_idx"] == 0 else "assistant",
        "text": item["utterance"],
        "emotion": item["context"]
    })

df_empathetic = pd.DataFrame(rows)
df_empathetic.to_csv("./data/empathetic_dialogues_test.csv", index=False)
# df_empathetic_val
df_empathetic

,dataset,conversation_id,role,text,emotion
0,empathetic_dialogues,hit:0_conv:0,user,Yeah about 10 years ago I had a horrifying exp...,guilty
1,empathetic_dialogues,hit:0_conv:0,assistant,Did you suffer any injuries?,guilty
2,empathetic_dialogues,hit:0_conv:0,user,No I wasn't hit. It turned out they were drunk...,guilty
3,empathetic_dialogues,hit:0_conv:0,assistant,Why did you feel guilty? People really shouldn...,guilty
4,empathetic_dialogues,hit:0_conv:0,user,I don't know I was new to driving and hadn't e...,guilty
...,...,...,...,...,...
10938,empathetic_dialogues,hit:12416_conv:24832,assistant,I live in Texas to so i know those feels,disgusted
10939,empathetic_dialogues,hit:12423_conv:24847,assistant,I have a big test on Monday_comma_ I am so ner...,anxious
10940,empathetic_dialogues,hit:12423_conv:24847,assistant,What is the test on?,anxious
10941,empathetic_dialogues,hit:12423_conv:24847,assistant,It's for my Chemistry class. I haven't slept m...,anxious
10942,empathetic_dialogues,hit:12423_conv:24847,assistant,Chemistry is quite difficult_comma_have you st...,anxious

## Daily_dialog

In [5]:
# daily_dialog = load_dataset("roskoN/dailydialog",trust_remote_code=True,download_mode="force_redownload")
# print("2")
# print(daily_dialog)
import kagglehub
from pathlib import Path

# Download latest version
path = kagglehub.dataset_download("thedevastator/dailydialog-unlock-the-conversation-potential-in")

print("Path to dataset files:", path)
data_dir = Path("./data")

Path to dataset files: /Users/godhanko/.cache/kagglehub/datasets/thedevastator/dailydialog-unlock-the-conversation-potential-in/versions/2

In [7]:
kagglehub.dataset_download(
    "thedevastator/dailydialog-unlock-the-conversation-potential-in",
    output_dir=str(data_dir / "dailydialog"),

)

Downloading to data/dailydialog/2.archive...

100%|██████████████████████████████████████| 2.46M/2.46M [00:00<00:00, 33.7MB/s]

Extracting files...

'data/dailydialog'

In [29]:
# rows = []

# for idx, item in enumerate(daily_dialog["train"]):
#         rows.append({
#             "dataset": "daily_dialog",
#             "conversation_id": item['id'],
#             "acts": item['acts'],
#             "text": item['utterances'],
#             "emotion": item["emotions"]
#         })

# df_daily = pd.DataFrame(rows)
# df_daily
# # df_daily.to_csv("daily_dialog.csv", index=False)

## GoEmotions

In [13]:
go_emotions = load_dataset("go_emotions",trust_remote_code=True)
print("3")
print(go_emotions)

3
DatasetDict({
    train: Dataset({
        features: ['text', 'labels', 'id'],
        num_rows: 43410
    })
    validation: Dataset({
        features: ['text', 'labels', 'id'],
        num_rows: 5426
    })
    test: Dataset({
        features: ['text', 'labels', 'id'],
        num_rows: 5427
    })
})

In [14]:
print(go_emotions["train"][0])

{'text': "My favourite food is anything I didn't have to cook myself.", 'labels': [27], 'id': 'eebbqej'}

In [24]:
rows = []

for idx, item in enumerate(go_emotions["train"]):
    rows.append({
        "dataset": "go_emotions",
        "conversation_id": idx,
        "role": "user",
        "text": item["text"],
        "emotion": item["labels"]  # list require to convert
    })

df_go = pd.DataFrame(rows)
df_go
df_go.to_csv("./data/go_emotions_train.csv", index=False)

In [25]:
rows = []

for idx, item in enumerate(go_emotions["validation"]):
    rows.append({
        "dataset": "go_emotions",
        "conversation_id": idx,
        "role": "user",
        "text": item["text"],
        "emotion": item["labels"]  # list require to convert
    })

df_go = pd.DataFrame(rows)
df_go
df_go.to_csv("./data/go_emotions_validation.csv", index=False)

In [26]:
rows = []

for idx, item in enumerate(go_emotions["test"]):
    rows.append({
        "dataset": "go_emotions",
        "conversation_id": idx,
        "role": "user",
        "text": item["text"],
        "emotion": item["labels"]  # list require to convert
    })

df_go = pd.DataFrame(rows)
df_go
df_go.to_csv("./data/go_emotions_test.csv", index=False)

In [27]:
import kagglehub


# Download latest version
path = kagglehub.dataset_download("thedevastator/dailydialog-unlock-the-conversation-potential-in")

print("Path to dataset files:", path)

Path to dataset files: /Users/godhanko/.cache/kagglehub/datasets/thedevastator/dailydialog-unlock-the-conversation-potential-in/versions/2

In [ ]:
pip install kagglehub